### ISSUE TITLE
Unclear "Unsupported Java" message

### ISSUE THREAD

**Issue by curiosity-a** [Scotsguy/background-cat#1]
From discussion in Discord:

`You're using Java 12, which is not supported.`
Should say "not supported by Forge/mods/whatever". Because as it is, it sounds like it's not supported by MMC.

**Comment by Scotsguy** [comment]
Fixed in [bfb4268](https://github.com/Scotsguy/parserbot/commit/bfb426893aec3eaa1c1f2b58f719b25cf3c467f4)  
[...] not supported by Minecraft
